import { CarType } from '../../services/car-service/types'

export interface IGarage {
    cars: CarType[],
    totalCount: number,
    init(): void,
}

export enum Selector {
    Body = 'body',
    NavigationTemp = '#navigation-temp',
    GarageMenuTemp = '#garage-menu-temp',
    ModelsList = '#models-list',
    GarageContentTemp = '#garage-content-temp',
    CarContentTemp = '#car-content-temp',
    TotalCount = '#total-count',
    GaragePage = '#garage-page',
    GarageContent = '#garage-content',
    CarsContainer = '.cars-container',
    Wrapper = '#wrapper',
    CarContent = '.car-content',
    CarName = '.car-name',
    IconUse = '.icon-use',
    ToGarage = '#to-garage',
    GarageMenu = '.garage-menu',
    ToWinners = '#to-winners',
    CreateButton = '#create-button',
    CreateName = '#create-name',
    CreateColor = '#create-color',
    UpdateButton = '#update-button',
    UpdateName = '#update-name',
    UpdateColor = '#update-color',
    Select = '.select',
    UpdateContainer = '.update-container',
    generateCars = '#generate-cars',
    PrevButtonGarage = '#garage-prev',
    NextButtonGarage = '#garage-next',
    WinnersContentTemp = '#winners-content-temp',
    WinnersPage = '#winners-page',
}